default: &default
  adapter: postgresql
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  host: localhost


test:
  adapter: postgresql
  encoding: unicode
  database: posgres
  pool: 5
  host: localhost

#
# development:
#   <<: *default
#   database: db/development.sqlite3
#
# test:
#   <<: *default
#   database: db/test.sqlite3

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
